---
apiVersion: v1
kind: Secret
metadata:
 name: secrets-data-publish
 labels:    
   app.kubernetes.io/name: data-publish
   app.kubernetes.io/instance: data-publish
type: Opaque
data:
  NGINX_USER: ********
  NGINX_PASSWORD: ************
  NGINX_HOST: aHR0cHM6Ly9hcnRlbWlzYS5pdGFpbm5vdmEuZXMv

---
apiVersion: v1
kind: Service
metadata:
 name: data-publish
spec:
 type: ClusterIP
 ports:
   - name: http
     port: 8900
     targetPort: http      
 selector:
   app.kubernetes.io/name: data-publish
   app.kubernetes.io/instance: data-publish

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-presentation
  labels:    
    app.kubernetes.io/name: data-presentation
    app.kubernetes.io/instance: data-presentation
    app.kubernetes.io/version: "8.1.0"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: data-publish
      app.kubernetes.io/instance: data-publish
      app: data-publish
  template:
    metadata:
      labels:
        app: data-publish
        app.kubernetes.io/name: data-publish
        app.kubernetes.io/instance: data-publish
        app.kubernetes.io/version: "8.1.0"
    spec:
      serviceAccountName: default      
      containers:
      - name: data-publish
        imagePullPolicy: IfNotPresent
        image: "datapublishmanager:1.0.1"
        ports:
          - name: http
            containerPort: 8900
            hostPort: 8900
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
        env:
          - name: NGINX_USER
            valueFrom:
                 secretKeyRef:
                   name: secrets-data-presentation
                   key: NGINX_USER                   
          - name: NGINX_PASSWORD
            valueFrom:
                 secretKeyRef:
                   name: secrets-data-presentation
                   key: NGINX_PASSWORD
          - name: NGINX_HOST
            valueFrom:
                 secretKeyRef:
                   name: secrets-data-presentation
                   key: NGINX_HOST
          - name: NGINX_WEB_SERVICE
            value: "prediction"                  
          - name: LOG_PATH
            value: "log/publish.log"
        ports:
        - name: http
          containerPort: 8900
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 300
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 3600
          successThreshold: 1
          timeoutSeconds: 10