apiVersion: batch/v1
kind: CronJob
metadata:
  name: crontabjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crontabjob
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - "curl 'http://datapublishmanager.itainnova.svc.cluster.local:8900/prediction'"
          restartPolicy: OnFailure
