---
apiVersion: v1
kind: Secret
metadata:
 name: secrets-data-presentation
 labels:    
   app.kubernetes.io/name: data-presentation
   app.kubernetes.io/instance: data-presentation
type: Opaque
data:
  POSTGRES_USER: *******
  POSTGRES_PWD: ***********************
  POSTGRES_DATABASE: *******
  POSTGRES_HOST: ***********************
  POSTGRES_PORT: ********

---
apiVersion: v1
kind: Service
metadata:
 name: data-presentation
spec:
 type: ClusterIP
 ports:
   - name: http
     port: 8800
     targetPort: http      
 selector:
   app.kubernetes.io/name: data-presentation
   app.kubernetes.io/instance: data-presentation








---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-presentation
  labels:    
    app.kubernetes.io/name: data-presentation
    app.kubernetes.io/instance: data-presentation
    app.kubernetes.io/version: "8.1.0"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: data-presentation
      app.kubernetes.io/instance: data-presentation
      app: data-presentation
  template:
    metadata:
      labels:
        app: data-presentation
        app.kubernetes.io/name: data-presentation
        app.kubernetes.io/instance: data-presentation
        app.kubernetes.io/version: "8.1.0"
    spec:
      serviceAccountName: default      
      containers:
      - name: data-presentation
        imagePullPolicy: IfNotPresent
        image: "datapresentationmanager:1.0.1"
        ports:
          - name: http
            containerPort: 8800
            hostPort: 8800
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
        env:
          - name: METEOROLOGICAL_DATABASE
            valueFrom:
                 secretKeyRef:
                   name: secrets-data-presentation
                   key: POSTGRES_DATABASE                   
          - name: METEOROLOGICAL_USER
            valueFrom:
                 secretKeyRef:
                   name: secrets-data-presentation
                   key: POSTGRES_USER
          - name: METEOROLOGICAL_PASSWORD
            valueFrom:
                 secretKeyRef:
                   name: secrets-data-presentation
                   key: POSTGRES_PWD
          - name: METEOROLOGICAL_HOST
            valueFrom:
                 secretKeyRef:
                   name: secrets-data-presentation
                   key: POSTGRES_HOST                   
          - name: METEOROLOGICAL_PORT
            valueFrom:
                 secretKeyRef:
                   name: secrets-data-presentation
                   key: POSTGRES_PORT
          - name: TMP_PATH
            value: "/tmp/"
          - name: OUTPUTCESGAFILENAME
            value: "output_cesga.csv"
          - name: OUTPUTCESGAFILENAMEDISEASE
            value: "output_disease_cesga.csv"
          - name: OUTPUTCESGAFILENAMEPHENOLOGY
            value: "output_phenology_cesga.csv"
          - name: CONFIGOUTPUTPATH
            value: '/data/dataPresentation/'
          - name: CONFIGOUTPUTPATH_4EMPTYFILES
            value: '/data/dataPresentation/emptyFiles'
          - name: COPYFILE
            value: "False"
          - name: LOGLEVEL
            value: "INFO"
        ports:
        - name: http
          containerPort: 8800
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthCheck
            port: http
          initialDelaySeconds: 30
          periodSeconds: 300
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthCheck
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 3600
          successThreshold: 1
          timeoutSeconds: 10